#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Sun Dec 29 11:24:04 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MVGUIFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MVGUIFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((464, 300))
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.text_ctrl_addr = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_inst = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.button_step = wx.Button(self.panel_1, wx.ID_ANY, "Step")
        self.list_ctrl_1 = wx.ListCtrl(self.panel_1, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_button_step, self.button_step)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MVGUIFrame.__set_properties
        self.SetTitle("frame")
        self.list_ctrl_1.InsertColumn(0, "Addr", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_ctrl_1.InsertColumn(1, "Mem", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_ctrl_1.InsertColumn(2, "Val", format=wx.LIST_FORMAT_LEFT, width=-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MVGUIFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.text_ctrl_addr, 0, 0, 0)
        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, ":")
        sizer_4.Add(label_1, 0, 0, 0)
        sizer_4.Add(self.text_ctrl_inst, 0, 0, 0)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)
        sizer_3.Add(self.button_step, 0, 0, 0)
        sizer_3.Add((0, 0), 0, 0, 0)
        sizer_3.Add((0, 0), 0, 0, 0)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)
        sizer_2.Add(self.list_ctrl_1, 1, wx.EXPAND, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def on_button_step(self, event):  # wxGlade: MVGUIFrame.<event_handler>
        print("Event handler 'on_button_step' not implemented!")
        event.Skip()

# end of class MVGUIFrame

class MVGUI(wx.App):
    def OnInit(self):
        self.frame = MVGUIFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MVGUI

if __name__ == "__main__":
    MVGUI = MVGUI(0)
    MVGUI.MainLoop()
